version: "3.9"
services:
  api:
    container_name: logistics-api
    build:
      context: ./
      dockerfile: src/Api/Logistics.WebApi/Dockerfile
      
    ports:
      - "7000:443"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443
  
  identity-server:
    container_name: logistics-identity
    build:
      context: ./
      dockerfile: src/Apps/Logistics.IdentityServer/Dockerfile
      
    ports:
      - "7001:443"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443
      
  admin-app:
    container_name: logistics-admin
    build:
      context: ./
      dockerfile: src/Apps/Logistics.AdminApp/Dockerfile
      
    ports:
      - "7002:443"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443