name: Deploy FTP

on:
  push:
    branches: [ "main" ]

env:
  WEB_API_PROJECT: src/Server/Logistics.API/Logistics.API.csproj
  IDENTITY_SERVER_PROJECT: src/Server/Logistics.IdentityServer/Logistics.IdentityServer.csproj
  ADMIN_APP_PROJECT: src/Client/Logistics.AdminApp/Logistics.AdminApp.csproj
  OFFICE_APP_PATH: src/Client/Logistics.OfficeApp
  OFFICE_APP_OUTPUT_PATH: dist/logistics.office-app

jobs:
  test-dotnet:
    name: .NET Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy-office-app:
    name: Deploy Office App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ${{ env.OFFICE_APP_PATH }}/package-lock.json
        
    - name: Install dependencies
      run: npm ci --prefix ${{ env.OFFICE_APP_PATH }} --force

    - name: Build
      run: npm run build --prefix ${{ env.OFFICE_APP_PATH }}

    - name: Deploy to host
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ${{ env.OFFICE_APP_PATH }}/${{ env.OFFICE_APP_OUTPUT_PATH }}/
        server-dir: office.jfleets.org/

  deploy-web-api:
    name: Deploy Web API
    runs-on: windows-latest
    needs: [test-dotnet]
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: dotnet publish ${{ env.WEB_API_PROJECT }} -c Release -r win-x86 -p:PublishSingleFile=true --self-contained true --output ./Release
    
    - name: Deploy to host
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: Release/
        server-dir: api.jfleets.org/

  deploy-identity-server:
    name: Deploy Identity Server
    runs-on: windows-latest
    needs: [test-dotnet]
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: dotnet publish ${{ env.IDENTITY_SERVER_PROJECT }} -c Release -r win-x86 -p:PublishSingleFile=true --self-contained true --output ./Release
    
    - name: Deploy to host
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: Release/
        server-dir: id.jfleets.org/

  deploy-admin-app:
    name: Deploy Admin App
    runs-on: windows-latest
    needs: [test-dotnet]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: dotnet publish ${{ env.ADMIN_APP_PROJECT }} -c Release -r win-x86 -p:PublishSingleFile=true --self-contained true --output ./Release
    
    - name: Deploy to host
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: Release/
        server-dir: admin.jfleets.org/