name: Office App Angular Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./src/Client/Logistics.OfficeApp/package-lock.json
        
    - name: Install dependencies
      run: npm ci --prefix ./src/Client/Logistics.OfficeApp --force

    - name: Build
      run: npm run build --prefix ./src/Client/Logistics.OfficeApp
